import type { NextPage } from "next";
import Head from "next/head";
import { SubmitHandler, useForm } from "react-hook-form";
import Input from "../components/input";

type Inputs = {
  spaceId: string;
  toReplace: string;
  replaceWith: string;
};
const Home: NextPage = () => {
  const {
    register,
    formState: { errors },
    handleSubmit,
  } = useForm<Inputs>({ mode: "onSubmit", reValidateMode: "onChange" });

  //const space = 138182;

  const onSubmit: SubmitHandler<Inputs> = async (inputs: Inputs) => {
    const { spaceId, toReplace, replaceWith } = inputs;
    await fetch(`/api/storyblok/${spaceId}`, {
      method: "POST",
      body: JSON.stringify({ toReplace, replaceWith }),
    });
  };

  return (
    <div className="flex flex-col w-full pt-6">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-4xl text-center">
        Storyblok string replacement example
      </h1>
      <span className="text-center mt-4">desc</span>

      <div className="px-8 flex items-center justify-center">
        <form
          className="flex flex-col p-8  max-w-2xl w-full  mt-16 justify-center items-center "
          onSubmit={handleSubmit(onSubmit)}
        >
          <Input
            label="Space ID"
            id="space-id-input"
            errorMsg={errors.spaceId?.message}
            type="number"
            register={register}
            name="spaceId"
          />

          <Input
            label="To replace"
            id="to-replace-input"
            errorMsg={errors.toReplace?.message}
            type="text"
            register={register}
            name="toReplace"
          />

          <Input
            label="Replace with"
            id="replace-with-input"
            errorMsg={errors.replaceWith?.message}
            type="text"
            name="replaceWith"
            register={register}
          />

          {/* add hover */}
          <input
            autoComplete="true"
            value="Replace"
            className="border rounded-lg border-gray-500  px-8 py-1 mt-6"
            type="submit"
          />
        </form>
      </div>
    </div>
  );
};

export default Home;
